language: php
php:
  - nightly
  - 7.3
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.5
  - 5.4

install:
  - composer install --no-interaction --no-progress

script:
  - composer test

notifications:
  email: false
  webhooks:
    - http://helit.org:8093/+sujevo-dev/showSuccessfulBuildMessages=always

jobs:
  include:
    - stage: checks
      php:
        - 7.2
      script:
        bash .travis/hasGitChanges.sh
